name: vacation_tracker
description: "Vacation Tracker App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  
  # --- State Management & Architecture ---
  flutter_bloc: ^8.1.3          # لإدارة الحالة (BLoC Pattern)
  equatable: ^2.0.5             # لمقارنة الكائنات بسهولة (ضروري للـ BLoC والـ Entities)
  dartz: ^0.10.1                # للبرمجة الوظيفية ومعالجة الأخطاء (Either و Unit)
  get_it: ^7.6.4                # لحقن الاعتماديات (Dependency Injection)

  # --- Database (Drift - SQLite) ---
  drift: ^2.14.1                # مكتبة قاعدة البيانات الرئيسية
  sqlite3_flutter_libs: ^0.5.18 # مكتبات التشغيل الأصلية لـ SQLite
  path_provider: ^2.1.1         # للوصول إلى مسارات التخزين في الجهاز (مجلد المستندات)
  path: ^1.8.3                  # للتعامل مع مسارات الملفات برمجياً

  # --- UI & Utilities ---
  intl: ^0.20.2                 # لتنسيق التواريخ (Date Formatting)
  google_fonts: ^6.1.0          # (اختياري) لاستخدام خطوط عصرية مثل Cairo أو Almarai
  flutter_localizations:        # لدعم اللغة العربية والاتجاه من اليمين لليسار (RTL)
    sdk: flutter
  share_plus: ^10.0.0           # إضافة حزمة المشاركة الحديثة

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- Code Generation ---
  build_runner: ^2.4.7           # المحرك الأساسي لتوليد الأكواد
  drift_dev: ^2.14.1             # لتوليد ملفات قاعدة البيانات الخاصة بـ Drift (ملفات .g.dart)

  # --- Code Quality ---
  flutter_lints: ^3.0.1           # قواعد تحليل الكود القياسية للحفاظ على نظافة الكود
  flutter_native_splash: ^2.4.7   # لتسريع عرض الشاشه الاساسيه عند بدء التطبيق
flutter:

  # Material Icons font is
  uses-material-design: true
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#F8F9FA" # لون الخلفية للوضع النهاري (Light Background)
  color_dark: "#121212" # لون الخلفية للوضع الليلي (Dark Background)
  
  android_12:
    color: "#F8F9FA"
    color_dark: "#121212"